### PR TITLE
Switched broken pypip.in badges to shields.io

### PR DESCRIPTION
**Pull request by movermeyer**
Hello, this is an auto-generated Pull Request. ([Feedback?](mailto:repobot@movermeyer.com?subject=pypip.in%20Badge%20Bot%20Feedback%3A%20wavefile))

Some time ago, [pypip.in](https://web.archive.org/web/20150318013508/https://pypip.in/) shut down. This broke the badges for a bunch of repositories, including `wavefile`. Thankfully, an equivalent service is run by [shields.io](https://shields.io). This pull request changes the badges to use shields.io instead.

### CODE REVIEW

**Comment by vokimon** [comment]
@movermeyer  pypip is working perfectly. What's the point of this? Are you trying to steal users from someone else service by means of bots?

**Comment by movermeyer** [comment]
After this happened, I got control of the pypip.in domain and made it simply redirect to shields.io.

So the badges now work again, but it costs money to operate the server, so I'd appreciate it if you could switch the links to point directly at shields.io

**Comment by vokimon** [comment]
So, you manage both services?

**Comment by movermeyer** [comment]
I currently control the pypip.in domain. I am not affiliated with shield.io at all.

1. A few years ago, pypip.in existed, It was run by someone (IDK who). They shut down and the domain name went up for sale.
1. All the pypip.in badges were broken, so I made a bot that detected them and made Pull requests to make the broken badges point at shields.io (which is a service someone else still runs that was similar to pypip.in
1. Once that was done, someone mentioned to me that I could have just bought the pypip.in domain and do the redirect. So I did.

I now own the pypip.in domain, which I have made redirect to shields.io (which I do not control). So while the pypip.in badges are fixed for now, they are really just redirects to shields.io (you can see this by looking at the Network tab of your browser's developer tools, hit F12).

But running the pypip.in server costs me money and I won't be doing it forever. It's a temporary fix while I get people to point directly at shields.io.

**Comment by vokimon** [comment]
Ok, thanks for the explanation. No problem, i pull it. Thanks.

**Pull request merged**
